services:
  db:
    image: postgres:15
    platform: linux/amd64
    container_name: techstore-db
    restart: always
    environment:
      POSTGRES_DB: techstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    image: lucasmatheus08/techstore-backend:v1
    platform: linux/amd64
    container_name: techstore-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/techstore
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      API_SECURITY_TOKEN_SECRET: ${JWT_SECRET}
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - db

  frontend:
    image: lucasmatheus08/techstore-frontend:v1
    platform: linux/amd64
    container_name: techstore-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend